// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmZKbq-e6uQunDdlZifio_sFklPIUuRRE',
    appId: '1:765658038570:web:92f4cab2755419fc6d5e53',
    messagingSenderId: '765658038570',
    projectId: 'cinebooking-a9550',
    authDomain: 'cinebooking-a9550.firebaseapp.com',
    storageBucket: 'cinebooking-a9550.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP9omUFX47RX-IK9fNQIoxmAK7cHyU_Bo',
    appId: '1:765658038570:android:633c9417e44a620a6d5e53',
    messagingSenderId: '765658038570',
    projectId: 'cinebooking-a9550',
    storageBucket: 'cinebooking-a9550.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfecOfLTpDQJMoB5MVi1NjozG1SQjkgNw',
    appId: '1:765658038570:ios:440927d40668af046d5e53',
    messagingSenderId: '765658038570',
    projectId: 'cinebooking-a9550',
    storageBucket: 'cinebooking-a9550.firebasestorage.app',
    iosBundleId: 'com.example.cinebooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfecOfLTpDQJMoB5MVi1NjozG1SQjkgNw',
    appId: '1:765658038570:ios:440927d40668af046d5e53',
    messagingSenderId: '765658038570',
    projectId: 'cinebooking-a9550',
    storageBucket: 'cinebooking-a9550.firebasestorage.app',
    iosBundleId: 'com.example.cinebooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmZKbq-e6uQunDdlZifio_sFklPIUuRRE',
    appId: '1:765658038570:web:993d2628415cd5ba6d5e53',
    messagingSenderId: '765658038570',
    projectId: 'cinebooking-a9550',
    authDomain: 'cinebooking-a9550.firebaseapp.com',
    storageBucket: 'cinebooking-a9550.firebasestorage.app',
  );

}